a=input("enter the first number: ")
a=float(a)
b=input("enter the second number: ")
b=float(b)
c= (a+b)
d= (a-b)
e=(a*b)
f=(a/b)

print('Addition: ',c)
print('Substraction: ',d)
print('Multiplication: ',e)
print('Division: ',f)
